checkout:
  post:
    - git submodule sync
    - git submodule update --init --recursive

machine:
  timezone: Asia/Tokyo

dependencies:
  pre:
    - go get -v github.com/spf13/hugo
    - git config --global user.name "ryoma-tokushige"
    - git config --global user.email "ryoma.tokushige@gmail.com"

deployment:
  master:
    branch: master
    commands:
      - git clone git@github.com:ryoma-tokushige/ryoma-tokushige.github.io.git
      - hugo
      - cd public && git add .
      - cd public && git commit -m "[ci skip] publish"
      - cd public && git push origin master